- snakebite/commandlineparser.py
If file for test operation doesn't exist snakebite _prints_ 'XXX: No
such file or directory', which is inconsistent with unix/hdfs test
command behaviour. In this patch make sure that if file doesn't exist
snakebite returns 1 as a command return code.
> Fix #115: test should communicate result only via return code

- snakebite/client.py
- snakebite/errors.py
- test/rename2_test.py
This patch adds another `mv`-primitive that is purposefully limited to
only rename and not moving of files. While this seldom is a problem when
interactively using the `mv` command. It often causes problems in
production environments when multiple programs do something like:
mv a dest
mv b dest  # Should throw error, but creates "dest/b" instead
Also, we're hoping to forever fix the plethora of luigi issues related
to atomicity in renaming that have arised:
* https://github.com/spotify/luigi/pull/393
* https://github.com/spotify/luigi/pull/522
* https://github.com/spotify/luigi/pull/557
And also the tons of tickets on Spotify's internal JIRA.
> Add client.rename_dont_move()

- requirements.txt
It seems like `setup.py` has the dependency `protobuf>2.4.1` specified
in `install_requires`.
Previously, when I ran `python setup.py test` (preceeded by a `sudo pip
install -r requirements.txt`), I got this as output:
~/spotify/repos/snakebite master
❯ python setup.py test
running test
Traceback (most recent call last):
File "setup.py", line 76, in <module>
cmdclass={'test': Tox}
File "/usr/lib/python2.7/distutils/core.py", line 152, in setup
dist.run_commands()
File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
self.run_command(cmd)
File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
cmd_obj.run()
File "/usr/lib/python2.7/dist-packages/setuptools/command/test.py", line 127, in run
self.distribution.fetch_build_eggs(self.distribution.install_requires) …
> Stricten version dependency on protobuf to >2.4.1

- snakebite/config.py
- test/config_test.py
- test/testconfig/conf/emr-core-site.xml
This is to accommodate snakebite to work on EMR cluster. All tests ran successfully. Added to test to see if the config is read correctly on config.py.
> Issue 113 - Snakebite unable to parse core-site.xml in EMR

- doc/source/cli.rst
- snakebite/client.py
Change the default port value (54310) of examples in documentation,
which it is not coherent with the Snakebite command line tools default
value (8020).
> Fix #137 use default namenode port in examples

- snakebite/formatter.py
- test/minicluster_testbase.py
- test/stat_test.py
Snakebite always prepended a leading 0 to permissions when using the 'stat'
command. This led to invalid permissions being returned. For example in cases
like "1777" it returned "01777". This is supposed to fix this case.
> FIX: Fix formatting of permissions with sticky bit

- snakebite/config.py
The current configuration retrieval assumes that when `HADOOP_HOME` is set, then it always contains config files. However, I run into a scenario when `HADOOP_HOME` is set, but config files are located somewhere else, i.e. in `/etc/hadoop/...`, in which case `get_external_config` isn't able to retrieve configuration.
I think it would be more flexible if we add `HADOOP_HOME` locations to `core_try_paths` and `hdfs_try_paths` in a way that they are checked first, but other locations are also tried in case no proper configuration was found.
> Search for configs in all locations

- snakebite/commandlineparser.py
- test/commandlineparser_test.py
For operations: mv, test and tail - single_arg is used to carry hdfs
path, and there's no extra dirs for this operations thus CL parsing
method skipped single_args - in this commit make sure single_arg is
always included for this operations.
> Fix #148 - make sure single_arg is used for CL parsing

- snakebite/commandlineparser.py
Piping the output of a snakebite command like text or cat to head results in a
broken pipe error when head closes the output pipe that snakebite was using.
This catches and ignores the exception, saving the user from a meaningless stack
trace after a successful series of commands.
> Handles broken pipe errors in snakebite commands

- snakebite/client.py
The current documentation states that HADOOP_PATH is used to determine additional
locations of configuration files. Instead HADOOP_HOME (and actually HADOOP_CONF_DIR, but
with this one I'm not sure if its consistently supported) is used. Also, it's worth
mentioning that core-site.xml is required for configuration as well to determine
default file-system name.
> Minor fix for doc of client.AutoConfigClient

- snakebite/client.py
- test/tail_test.py
Previously it was hardcoded to 1KB:
- Currently supports up to the hadoop server block size - simply because it was simpler to implement. If the need to longer tail will arise, it could be implemented as well. It also tests that the tail_length input is positive.
- To read the block size, we use client.serverdefaults(). However, in order to prevent every call to tail() from also querying the server, I implemented simple caching of the result in client.serverdefaults()
- client.serverdefaults() also has a force_reload flag that allows to reload the saved values either way, and returns a copy of the result from the server so that the user can't change it.
If you feel the server defaults often change during the lifetime of an instance of client, I have a few ideas in mind:
1. Keep track of …
> Added tail length to the client.tail method

- requirements.txt
- setup.py
- snakebite/channel.py
- snakebite/client.py
- snakebite/commandlineparser.py
- snakebite/config.py
- snakebite/kerberos.py
- snakebite/rpc_sasl.py
- snakebite/service.py
This patch implements SASL authentication (only GSSAPI was tested). SASL authentication is required for secure clusters, specifically the ones that use Kerberos. In Hadoop SASL is implemented on top of the Hadoop RPC protocol. I have chosen not to refactor any of the code yet, that could be done in a later patch.
* Dependencies on sasl and python-krbV are added
> Add SASL authentication

- snakebite/channel.py
- snakebite/client.py
- snakebite/commandlineparser.py
- snakebite/platformutils.py
- test/commandlineparser_test.py
- test/delete_test.py
allowing the library to be imported on Windows. Fixes #162
Note that this is probably not the only Windows-compatibility problem. I will file more issues and submit more pull requests as I discover problems.
> Wraps use of the Python 'pwd' module in a utility procedure

- README.rst
- debian/changelog
- requirements.txt
- setup.py
- snakebite/channel.py
- snakebite/version.py
There are issues with building snakebite since the dependency is on python-krbV, which in it's turn needs the header files for kerberos. This makes kerberos support optional and installable through `pip install "snakebite[kerberos]"`
> Make kerberos optional

- snakebite/client.py
Since windows is broken, os.path on that platform uses \ instead of /
> Start using posixpath where appropriate.

- snakebite/channel.py
- snakebite/client.py
- snakebite/commandlineparser.py
- snakebite/config.py
- snakebite/rpc_sasl.py
- snakebite/service.py
- test/client_test.py
- test/commandlineparser_test.py
- test/config_test.py
This is related to this issue: https://github.com/spotify/snakebite/issues/175
See this comment: https://github.com/spotify/snakebite/issues/175#issuecomment-185966102
This might not be the ideal way since removing the side effects [here](https://github.com/spotify/snakebite/blob/master/snakebite/config.py#L94) and [here] (https://github.com/spotify/snakebite/blob/master/snakebite/config.py#L90) might be a better solution. 
Let me know if this pull request makes sense and really appreciate your great work on the library!
> Handle hdfs_namenode_principal properly and refactor auto configuration logic

- snakebite/channel.py
- snakebite/client.py
- snakebite/errors.py
- test/client_test.py
First of all its useful to differentiate snakebite exceptions from other using common base class - so all snakebite exceptions could be caught without need to support error-prone list of exception classes in user code.
Secondly, its helpful to differentiate transient errors (e.g. network-related problems), so user code could apply custom retry policy instead of failing entire peace of work altogether.
I have to confess I was't sure about SASL code, so exceptions in rpc_sasl.py left unchanged.
And I should note that differentiating exceptions has to be done in new and edited code on a constant basis for it to work.
> Common base class for exceptions; differentiating transient and fatal exceptions

- README.md
- snakebite/client.py
- test/client_test.py
https://github.com/spotify/snakebite/pull/189 differentiated transient and fatal exceptions. In [this case](https://github.com/spotify/snakebite/pull/189/files#diff-d9827893b8ca9a0f86a685a5fd2327b5L1383) `OutOfNNException` was replaced with `InvalidInputException` to conform to this new distinction. The similar case in the child constructor was probably forgotten to be changed and this PR fixes it up.
The only remaining question is whether `InvalidInputException` is still appropriate, or:
1) A new `InvalidConfigException` should be introduced
2) The more general `FatalException` should be used
> Use InvalidInputException instead of OutOfNNException.

- snakebite/commandlineparser.py
- test/commandlineparser_test.py
For when your remote hdfs user is not the same as your local user.
The API was already there, I just passed 'user' along in the config.
> Adding user as a config option (.snakebiterc)

- snakebite/client.py
The lack of this parameter causes a bug when using copyToLocal to copy a file from a Linux HDFS cluster to a Windows client box. The file that ends up on Windows isn't byte-identical to the starting file on Linux, due to some end-of-line conversion issue.
BTW: This is literally a one-character change, so I didn't bother to open an issue first. Let me know if you'd prefer to have an issue and I can create one.
> Changing the 'open' command to open a temporary file as binary.

- snakebite/channel.py
- snakebite/client.py
- snakebite/commandlineparser.py
- snakebite/config.py
- snakebite/service.py
- test/client_test.py
- test/config_test.py
- test/testconfig/conf/ha-retry-hdfs-site.xml
Add a request retry logic for connection failures. Use the retry value from the Hadoop configuration if set. This enables the client to not fail in case the NameNode RPC queues are full. The retry logic and its default settings are the same as in the original Java HdfsClient. The calculation of sleep interval was simply ported to Python. Successful requests might be repeated in case of network failures but this is the same in the vanilla Hadoop implementation and the NameNode interfaces are designed to handle this by either being idempotent (see ClientProtocol @Idempotent annotations) or failing upon the second request, e.g. double creations.
Configure the channel socket to use the socket timeout as configured for Hadoop after establishing the connection. This helps to not time out when …
> Increase client robusteness by adding retry and request timeout

- README.md
- doc/source/development.rst
- doc/source/testing.rst
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
> Convert readthedocs links for their .org -> .io migration for hosted projects

- snakebite/channel.py
- snakebite/client.py
- snakebite/errors.py
- test/client_test.py
Currently the client will fail on any block read errors even
though these might be transient failures. This patch enables
the client to retry block read failures to make it more
failure tolerant.
> Add client retry for block read failures

- snakebite/client.py
- snakebite/commandlineparser.py
- snakebite/config.py
- test/commandlineparser_test.py
- test/config_test.py
- test/testconfig/conf/use-datanode-hostname-hdfs-site.xml
When reading blocks, client talks to datanode by default using the datanode's
IP address returned by the name node. The problem with this approach is that
the IP address is a private IP within the cluster, so the client won't works if
it is in a different network. This commit updates the config module to support
`dfs.client.use.datanode.hostname` config property, and have the clients to use
this property to determine weather to use the IP address or the hostname to
talk to datanodes.
> Support dfs.client.use.datanode.hostname config property

- snakebite/client.py
- snakebite/config.py
This supports the use-datanode-hostname feature and is also able to read it from hadoop config file.
Implementation is a backport of what was done in master branch (pull request #210 ) while taking into account legacy code limitations.
Tested to work (unfortunately there were no relevant unittests that I could easily extend).
It would be great to merge this and bump version to 1.3.13
> Backporting pull request #210 (Support dfs.client.use.datanode.hostname config property) for v1.3
